#!/usr/bin/env bash
#Bash script that will display information about subdomains

Subdomain_information () {
	data=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' |
			tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $data" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  subdomain_information "$1" "www"
  subdomain_information "$1" "lb-01"
  subdomain_information "$1" "web-01"
  subdomain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  subdomain_information "$1" "$2"
fi
