#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '37i\\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n' /etc/nginx/sites-available/default
service nginx restart
