#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
#that contains the string Ceci n'est pas une page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i "37i\\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n" "/etc/nginx/sites-available/default"
echo "Ceci n'est pas une page" > "/usr/share/nginx/html/404error.html"
sed -i "37i\ \n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" "/etc/nginx/sites-available/default"
service nginx restart
