#!/usr/bin/env bash
#configures a brand new Ubuntu machine to the requirements
file="/etc/nginx/sites-available/default"
fileError="/usr/share/nginx/html/404error.html"
reDirection="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
reDirectionError="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
tadHeader="\n\tadd_header X-Served-By $hostname;\n"
text="Hello World!"
ceci="Ceci n'est pas une page"

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "$text" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $reDirection" "$file"
echo "$ceci" > "$fileError"
sed -i "37i\ $reDirectionError" "$file"
sed -i "37i\ $tadHeader" "$file"
service nginx restart