#!/usr/bin/env bash
# pings an IP address passed as an argument

DisplayUsage() {
    echo "Usage: $0 {IP_ADDRESS}"
}

Ping() {
    IP_Address="$1"
    ping -c 5 "$IP_Address"
}

main() {

    if [ $# -eq 0 ]; then
        DisplayUsage
        exit 1
    fi

    if ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        DisplayUsage
        exit 1
    fi

    Ping "$1"
}

main "$@"

