#!/usr/bin/env bash
#Bash script that fixes what's preventing Nginx installation
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart