#!/usr/bin/env bash
# Displays the PID, along with the process name, of processes whose name contain the word bash

LIST=$(pgrep -f bash)

for i in $LIST;
do
    process=$(ps -p "$i" -o comm=)
    echo "$i $process"
done
