#!/usr/bin/env bash
# Displays the content of the current directory in a list format where only the part of the name after the first dash is displayed.

List=$(ls)
for file in $List; do
        echo "$file" | cut -d '-' -f2
done
